# Spring Boot configuration
spring:

  profiles:
    active: development
  # Database
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    initialization-mode: always
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: create-drop # When you launch the application for the first put "none" instead of "create-drop" or "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true


server:
  port : ${PORT:8088}